In [7]:
import numpy as np
A=np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [8]:
array =np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np
import math
array =np.ones((1,5)) 
print(array)
array2=np.random.randn((2))
print(array2)

[[1. 1. 1. 1. 1.]]
[-0.75668225  2.05201328]


In [15]:
friends=["Osman","Kemal","Kaan"]
for x in friends:
    print(x)

Osman
Kemal
Kaan


In [30]:
import numpy as np
from numpy import random
x=random.randint(100)
print(x)
if x>=90:
    print("AA")
elif x>=80:
    print("BB")
elif x>=70:
    print("CC")
elif x>=60:
    print("DD")
elif x>=50:
    print("DD")
else:
    print("FF")

87
BB
